<?php
/**
 * Copyright (c) 2017. Volodumur Hryvinskyi
 * @author   Volodumur Hryvinskyi <script@email.ua>
 * @package  scriptua\lp
 */
?>
<div class="container">
    <div class="row">
        <div class="footer">
            <div class="menus">
                <div class="container-fluid">
                    <div class="row">
                        <?php echo $this->getChildHtml() ?>
                    </div>
                </div>
            </div>
            <div class="copyright"><?php echo $this->getCopyright() ?></div>
        </div>
    </div>
</div>