<?php
/**
 * Copyright (c) 2017. Volodumur Hryvinskyi
 * @author   Volodumur Hryvinskyi <script@email.ua>
 * @package  scriptua\lp
 */
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<header class="header">
    <div class="top-block">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="row">
                        <?php echo $this->getChildHtml('topLinks') ?>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="row">
                        <div class="pull-right">
                            <?php echo $this->getChildHtml('store_language') ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="nav-bar">
        <div class="container">
            <div class="row">
                <div class="nav-bar__wrap">
                    <div class="pull-left">
                        <p class="welcome-msg"><?php echo $this->getChildHtml('welcome') ?><?php echo $this->getAdditionalHtml() ?></p>
                    </div>
                    <div class="pull-right">
                        <?php echo $this->getChildHtml('navbarLinks') ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="logo">
                <?php if ($this->getIsHomePage()): ?>
                    <h1 class="logo__text">LP</h1>
                <?php else: ?>
                    <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo__text">LP</a>
                <?php endif ?>
            </div>
            <div class="quick-access">
                <?php echo $this->getChildHtml('topSearch') ?>
            </div>
            <?php echo $this->getChildHtml('topContainer'); ?>
        </div>
    </div>
</header>
<?php echo $this->getChildHtml('topMenu') ?>
