<?php
/**
 * Copyright (c) 2017. Volodumur Hryvinskyi
 * @author   Volodumur Hryvinskyi <script@email.ua>
 * @package  scriptua\lp
 */

$isLogged = Mage::getSingleton('customer/session')->isLoggedIn();
?>
<div class="reviews">
    <div class="reviews__header">
        <div class="clearfix">
            <div class="pull-left">
                <h1>Testimonials</h1>
            </div>
            <div class="pull-right">
                <button <?php //echo !$isLogged ? 'disabled' : '' ?> class="btn btn-success" data-toggle="collapse" data-target=".reviews_form">
                    Submit Your Testimonial
                </button>
            </div>
        </div>
    </div>

    <?php echo $this->getBlockHtml('lp_reviews_form')  ?>

    <div class="reviews__description">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, at aut blanditiis consequuntur dolorum ea
        expedita facilis inventore labore officiis perspiciatis quae quam quos reprehenderit similique suscipit
        temporibus veritatis? Ab accusamus aliquid aut autem, cumque delectus dolore eaque exercitationem illo
        impedit iste minima molestias natus quae quos saepe vero voluptatibus!
    </div>

    <?php echo $this->getBlockHtml('lp_reviews_items') ?>
</div>
