<?php
/**
 * Copyright (c) 2017. Volodumur Hryvinskyi
 * @author   Volodumur Hryvinskyi <script@email.ua>
 * @package  scriptua\lp
 */

/**
 * $this Lp_Reviews_Block_Items
 */

$collection = $this->getCollection();
?>

<table class="data-table" id="my-custom-table">
    <thead>
    <tr>
        <th><?php echo $this->__('Title') ?></th>
        <th><span class="nobr"><?php echo $this->__('Created at') ?></span></th>
    </tr>
    </thead>
    <tbody>
    <?php $_odd = ''; ?>
    <?php foreach ($collection as $item): ?>
        <tr>
            <td><span class="nobr"><?php echo $item->getContent(); ?></span></td>
            <td><?php echo $this->formatDate($item->getCreatedAt()) ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->getToolbarHtml(); ?>
