<?php
/**
 * Copyright (c) 2017. Volodumur Hryvinskyi
 * @author   Volodumur Hryvinskyi <script@email.ua>
 * @package  scriptua\lp
 */

/**
 * $this Lp_Reviews_Block_Items
 */

$collection = $this->getCollection();

?>

<div class="reviews_items">
    <?php foreach ($collection as $item): ?>
        <?php /** @var $item Lp_Reviews_Model_Reviews */ ?>
        <div class="item">
            <div class="content">
                <?php echo $item->getData('content'); ?>
            </div>
            <time class="datetime">
                <span class="nobr"><?php echo $this->__('Created at') ?></span>
                <?php echo $item->getData('created_at') ?>
            </time>
            <div class="name">
                <?php echo $item->getData('fullname') ?>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<?php echo $this->getToolbarHtml(); ?>
