<?php
/**
 * Copyright (c) 2017. Volodumur Hryvinskyi
 * @author   Volodumur Hryvinskyi <script@email.ua>
 * @package  scriptua\lp
 */

/**
 * $this Lp_Reviews_Block_Items
 */

$collection = $this->getCollection();

?>

<div class="reviews_items">
    <?php foreach ($collection as $item): ?>
        <?php /** @var $item Lp_Reviews_Model_Reviews */ ?>
        <div class="item">
            <div class="content">
                <?php echo $item->getData('content'); ?>
                <time class="date label label-info">
<!--                    <span class="nobr">--><?php //echo $this->__('Created:') ?><!--</span>-->
                    <?php echo date('Y-m-d', strtotime($item->getData('created_at'))) ?>
                </time>
            </div>
            <div class="name">
                <?php echo $item->getData('fullname') ?>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<?php echo $this->getToolbarHtml(); ?>
