<?php
/**
 * Copyright (c) 2017. Volodumur Hryvinskyi
 * @author   Volodumur Hryvinskyi <script@email.ua>
 * @package  scriptua\lp
 */

?>

<?php if($this->getCollection()->getSize()): ?>

    <?php if($this->getUseContainer()): ?>
        <div class="clearfix container-fluid">
    <?php endif ?>

    <div class="pull-left">
        <?php if($this->getShowAmounts()): ?>
            <p class="amount pull-left">
                <?php if($this->getLastPageNum()>1): ?>
                    <?php echo $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
                <?php else: ?>
                    <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
                <?php endif; ?>
            </p>
        <?php endif ?>

        <?php if($this->getShowPerPage()): ?>
            <div class="limiter">
                <label><?php echo $this->__('Show') ?></label>
                <select onchange="setLocation(this.value)">
                    <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                        <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                            <?php echo $_limit ?>
                        </option>
                    <?php endforeach; ?>
                </select> <?php echo $this->__('per page') ?>
            </div>
        <?php endif ?>
    </div>

    <?php if($this->getLastPageNum()>1): ?>
        <div class="">
            <strong><?php echo $this->__('Page:') ?></strong>
            <ul class="pagination">
                <?php if (!$this->isFirstPage()): ?>
                    <li>
                        <a class="previous<?php if(!$this->getAnchorTextForPrevious()): ?> i-previous<?php endif;?>" href="<?php echo $this->getPreviousPageUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Previous')) ?>">
                           <
                        </a>
                    </li>
                <?php endif;?>

                <?php if ($this->canShowFirst()): ?>
                    <li><a class="first" href="<?php echo $this->getFirstPageUrl() ?>">1</a></li>
                <?php endif;?>

                <?php if ($this->canShowPreviousJump()): ?>
                    <li><a class="previous_jump" title="" href="<?php echo $this->getPreviousJumpUrl() ?>">...</a></li>
                <?php endif;?>

                <?php foreach ($this->getFramePages() as $_page): ?>
                    <?php if ($this->isPageCurrent($_page)): ?>
                        <li class="current"><a href="#"><?php echo $_page ?></a></li>
                    <?php else: ?>
                        <li><a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
                    <?php endif;?>
                <?php endforeach;?>


                <?php if ($this->canShowNextJump()): ?>
                    <li><a class="next_jump" title="" href="<?php echo $this->getNextJumpUrl() ?>">...</a></li>
                <?php endif;?>

                <?php if ($this->canShowLast()): ?>
                    <li><a class="last" href="<?php echo $this->getLastPageUrl() ?>"><?php echo $this->getLastPageNum() ?></a></li>
                <?php endif;?>

                <?php if (!$this->isLastPage()): ?>
                    <li>
                        <a class="next<?php if(!$this->getAnchorTextForNext()): ?> i-next<?php endif; ?>" href="<?php echo $this->getNextPageUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Next')) ?>">
                            >
                        </a>
                    </li>
                <?php endif;?>
            </ul>

        </div>
    <?php endif; ?>

    <?php if($this->getUseContainer()): ?>
        </div>
    <?php endif ?>

<?php endif ?>
